### ISSUE TITLE
MissingPluginException(No implementation found for method initSoundpool on channel pl.ukaszapps/soundpool)

### ISSUE THREAD

**Issue by gracegyu** [ukasz123/soundpool#107]
hello. I'm making a game with Flutter and trying to add sound effects using soundpool. However, the following error occurs in the rootBundle.load function.

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: MissingPluginException(No implementation found for method initSoundpool on channel pl.ukaszapps/soundpool)
flutter: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:7)
<asynchronous suspension>
#1      Soundpool._connect (package:soundpool/soundpool.dart:290:20)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

my code is here

```
import 'package:soundpool/soundpool.dart';

  Soundpool _pool = Soundpool(streamType: StreamType.notification);
  int soundIdClick;
  soundIdClick = await rootBundle.load("assets/sound/click.mp3").then((ByteData soundData) {
-----> error message
        return _pool.load(soundData);
  });

 //// ......

  void playSoundClick() async {
    if (gSettingData.isSound) await _pool.play(soundIdClick);
  }


```

---------------------------------

**Comment by MrCsabaToth** [comment]
Is this in debug mode or only in release?

**Comment by umanamente** [comment]
I have the same error when building for **Windows** platform, and it occurs for **Debug** mode as well.
