### ISSUE TITLE
build: soundpool.dart:288:48: Error: Too few positional arguments: 3 required, 2 given.

### ISSUE THREAD

**Issue by calcitem** [ukasz123/soundpool#71]
Hi,

https://github.com/calcitem/Sanmill/runs/2699121824?check_suite_focus=true build pass.
One day later, I use almost same source code rebuild again, however, build failed.
https://github.com/calcitem/Sanmill/runs/2703446669?check_suite_focus=true

I don't know why. 

Can https://github.com/ukasz123/soundpool/commit/6c05ac06806bcce813a579df0664e8d3da8fc10c slove this issue?

Thanks!

Build error log:

```shell
[        ] [  +16 ms] /opt/hostedtoolcache/flutter/2.2.1-stable/x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/hostedtoolcache/flutter/2.2.1-stable/x64/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/hostedtoolcache/flutter/2.2.1-stable/x64/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages /home/runner/work/Sanmill/Sanmill/src/ui/flutter_app/.dart_tool/package_config.json --output-dill /home/runner/work/Sanmill/Sanmill/src/ui/flutter_app/.dart_tool/flutter_build/bcee474ba3777f5405a824293a9c54dc/app.dill --depfile /home/runner/work/Sanmill/Sanmill/src/ui/flutter_app/.dart_tool/flutter_build/bcee474ba3777f5405a824293a9c54dc/kernel_snapshot.d package:sanmill/main.dart
[+6489 ms] [+7387 ms] /opt/hostedtoolcache/flutter/2.2.1-stable/x64/.pub-cache/hosted/pub.dartlang.org/soundpool-2.0.0-nullsafety.0/lib/soundpool.dart:288:48: Error: Too few positional arguments: 3 required, 2 given.
[   +7 ms] [   +1 ms]     final int id = await _platformInstance.init(_streamType.index, _maxStreams);
[        ] [        ]                                                ^
[+10183 ms] [+10142 ms] Persisting file store
[        ] [   +2 ms] Done persisting file store
[        ] [  +18 ms] "flutter assemble" took 18,008ms.
[        ] [   +2 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] > Task :app:compileFlutterBuildRelease FAILED
[        ] [   +2 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:291:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]            <asynchronous suspension>
[        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +4 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[  +89 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/opt/hostedtoolcache/flutter/2.2.1-stable/x64/packages/flutter_tools/gradle/flutter.gradle' line: 1035
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/opt/hostedtoolcache/flutter/2.2.1-stable/x64/bin/flutter'' finished with non-zero exit value 1
[   +1 ms] * Try:
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] * Get more help at https://help.gradle.org
[        ] See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD FAILED in 2m 15s
```

I try to modify code to use new node:
https://github.com/calcitem/Sanmill/commit/22cdedad59bc19604cf09b7c54b524a7ac78adba
And build again, buit failed:
https://github.com/calcitem/Sanmill/runs/2703505085?check_suite_focus=true

```shell
[        ] FINE: Resolving dependencies finished (1.579s).
[        ] ERR : Error on line 17, column 11: Invalid description in the "soundpool" pubspec on the "soundpool_web" dependency: "../soundpool_web" is a relative path, but this isn't a local pubspec.
[        ]     |    ╷
[        ]     | 17 │     path: ../soundpool_web
[        ]     |    │           ^^^^^^^^^^^^^^^^
[        ]     |    ╵
```

So how to modify pubspec.yaml to use unmerged branch to try it ?

Thanks a lot!

**Comment by allanclempe** [comment]
same here.

Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (4 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

```cmd
Running Gradle task 'assembleUatRelease'...                     
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/soundpool-2.0.0-nullsafety.0/lib/soundpool.dart:288:48: Error: Too few positional arguments: 3 required, 2 given.

    final int id = await _platformInstance.init(_streamType.index, _maxStreams);
```

I'm using soundpool: 2.0.0-nullsafety.0

Thanks

**Comment by calcitem** [comment]
Workaround fix
https://github.com/calcitem/Sanmill/commit/4fba30145923054b107ee5a2367e207b76060b1c

Looking forward to the official hotfix, thanks!

**Comment by ukasz123** [comment]
@calcitem Thanks for the workaround.

You can also try to add following override:

```
dependency_overrides:
  soundpool_platform_interface: 2.0.0-nullsafety.0
```

**Comment by ukasz123** [comment]
Alternatively just update to version `^2.1.0`

**Comment by calcitem** [comment]
Upgraded. Thank you!
