### ISSUE TITLE
Build failed on ios

### ISSUE THREAD

**Issue by indiepaul** [ukasz123/soundpool#8]
> Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.                                            1.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET soundpool OF PROJECT Pods WITH CONFIGURATION Debug ===
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)

**Comment by ukasz123** [comment]
@indiepaul Could you provide some extra information about the problem? I tried to build the project in the XCode myself and there was no issue.

**Comment by kiruto** [comment]
Same issue here.
I tried to build with swift version 4, 4.2 and 5, also got the same error message.

**Comment by kiruto** [comment]
```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Pods/.symlinks/flutter/ios`
    -> Fetching podspec for `soundpool` from `Pods/.symlinks/plugins/soundpool/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A soundpool

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing soundpool (0.0.1)
      - Running pre install hooks
        - Podfile

    Generating Pods project
      - Creating Pods project
      - Adding source files to Pods project
      - Adding frameworks to Pods project
      - Adding libraries to Pods project
      - Adding resources to Pods project
      - Adding development pod helper files to Pods project
      - Linking headers
      - Installing targets
        - Installing target `Flutter` iOS 8.0
        - Installing target `soundpool` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/soundpool/soundpool.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/soundpool/soundpool-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/soundpool/soundpool-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/soundpool/soundpool-dummy.m`
        - Installing target `Pods-Runner` iOS 9.0
          - Generating Info.plist file at `Pods/Target Support Files/Pods-Runner/Pods-Runner-Info.plist`
          - Generating module map file at `Pods/Target Support Files/Pods-Runner/Pods-Runner.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/Pods-Runner/Pods-Runner-umbrella.h`
          - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
      - Running post install hooks
    [!] An error occurred while processing the post-install hook of the Podfile.

    undefined method `headers_build_phase' for <PBXAggregateTarget name=`Flutter` UUID=`000000000290`>:Xcodeproj::Project::Object::PBXAggregateTarget

    /Users/tatsu/projects/flutter-tetris/ios/Podfile:70:in `block (3 levels) in from_ruby'
    /Users/tatsu/projects/flutter-tetris/ios/Podfile:65:in `each'
    /Users/tatsu/projects/flutter-tetris/ios/Podfile:65:in `block (2 levels) in from_ruby'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.0.beta.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:685:in `run_podfile_post_install_hook'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:673:in `block in run_podfile_post_install_hooks'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:145:in `message'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:672:in `run_podfile_post_install_hooks'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:197:in `block in generate_pods_project'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:194:in `generate_pods_project'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:125:in `install!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:687:in `rescue in run_podfile_post_install_hook'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:684:in `run_podfile_post_install_hook'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:673:in `block in run_podfile_post_install_hooks'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:145:in `message'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:672:in `run_podfile_post_install_hooks'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:197:in `block in generate_pods_project'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:194:in `generate_pods_project'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:125:in `install!'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
```

**Comment by dwolvin** [comment]
Same issue. On opening the project in XCode 10.2 I see this:
![Screen Shot 2019-04-05 at 12 41 33 PM](https://user-images.githubusercontent.com/2250015/55643112-555c3180-57a0-11e9-8c43-525145b9e351.png)

**Comment by ukasz123** [comment]
It seems that the problem was the Swift version the plugin was using. Please, check #11 if it solves the problem.
